version: '2'
services:
  web:
    build: .
    volumes:
      - .:/app
    links:
      - mongodb
      - redis
    ports:
      - "80:3000"
  redis:
    image: tutum/redis
  mongodb:
    image: tutum/mongodb
