version: '2'
services:
  web:
    build: .
    volumes:
      - .:/app
    links:
      - mongodb
      - redis
    ports:
      - "80:3000"
    environment:
      - MONGODB_URL=mongodb://btg:${BTG_PASS}@mongodb/btg
      - REDIS_URL=redis://:${BTG_PASS}@redis
  redis:
    image: tutum/redis
    environment:
      - REDIS_PASS=${BTG_PASS}
  mongodb:
    image: tutum/mongodb:3.2
    environment:
      - MONGODB_PASS=${BTG_PASS}
      - MONGODB_DATABASE=btg
      - MONGODB_USER=btg
